# Generated by Django 5.0.4 on 2024-05-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
