# Generated by Django 5.0.4 on 2024-05-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_user_picture_url_blogcontent_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontent',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='blogcontent',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='blog_id',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
