# Generated by Django 5.0.6 on 2024-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_blog_id_blogcontent_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.ImageField(blank=True, default='media/profile-pics/default.jpg', upload_to='media/profile-pics/'),
        ),
    ]
