# Generated by Django 5.0.6 on 2024-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/hzrmzkuce/image/upload/v1/media/profile-pics/default_b1yap4', upload_to='media/profile-pics/'),
        ),
    ]
