title: "Champions' Chronicle"
description: "Your site description."
baseurl: "" # le sous-chemin de votre site, par exemple /blog
url: "" 


exclude:
  - "node_modules"
  - "vendor"
  - ".bundle"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

include:
  - "_pages"
  - "_posts"
  - "assets"
  - "index.html"

# Configuration du processeur Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block: false
